[env:esp32s3-usb]
platform = pioarduino/esp32
board = esp32-s3-devkitc-1
framework = arduino
board_build.flash_size = 16MB
board_build.psram_type = opi
board_build.partitions = default_16MB.csv
lib_deps = lvgl/lvgl@9.2.2
build_flags =
  -D ARDUINO_USB_CDC_ON_BOOT=1
  -D LV_CONF_INCLUDE_SIMPLE
monitor_speed = 115200
monitor_filters = esp32_exception_decoder
